// Generated by gencpp from file tircgo_uart/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TIRCGO_UART_MESSAGE_ADDTWOINTS_H
#define TIRCGO_UART_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <tircgo_uart/AddTwoIntsRequest.h>
#include <tircgo_uart/AddTwoIntsResponse.h>


namespace tircgo_uart
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace tircgo_uart


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tircgo_uart::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tircgo_uart::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::tircgo_uart::AddTwoInts > {
  static const char* value()
  {
    return "tircgo_uart/AddTwoInts";
  }

  static const char* value(const ::tircgo_uart::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tircgo_uart::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::tircgo_uart::AddTwoInts >
template<>
struct MD5Sum< ::tircgo_uart::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tircgo_uart::AddTwoInts >::value();
  }
  static const char* value(const ::tircgo_uart::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tircgo_uart::AddTwoIntsRequest> should match
// service_traits::DataType< ::tircgo_uart::AddTwoInts >
template<>
struct DataType< ::tircgo_uart::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tircgo_uart::AddTwoInts >::value();
  }
  static const char* value(const ::tircgo_uart::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tircgo_uart::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::tircgo_uart::AddTwoInts >
template<>
struct MD5Sum< ::tircgo_uart::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tircgo_uart::AddTwoInts >::value();
  }
  static const char* value(const ::tircgo_uart::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tircgo_uart::AddTwoIntsResponse> should match
// service_traits::DataType< ::tircgo_uart::AddTwoInts >
template<>
struct DataType< ::tircgo_uart::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tircgo_uart::AddTwoInts >::value();
  }
  static const char* value(const ::tircgo_uart::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIRCGO_UART_MESSAGE_ADDTWOINTS_H
