// Generated by gencpp from file tircgo_uart/RobotStatus.msg
// DO NOT EDIT!


#ifndef TIRCGO_UART_MESSAGE_ROBOTSTATUS_H
#define TIRCGO_UART_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tircgo_uart/Tracking_status_reply.h>
#include <tircgo_uart/Lidar_level_reply.h>

namespace tircgo_uart
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : header()
    , is_activated(false)
    , now_mode(0)
    , tracking_status_reply()
    , lidar_level_reply()  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_activated(false)
    , now_mode(0)
    , tracking_status_reply(_alloc)
    , lidar_level_reply(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_activated_type;
  _is_activated_type is_activated;

   typedef int16_t _now_mode_type;
  _now_mode_type now_mode;

   typedef  ::tircgo_uart::Tracking_status_reply_<ContainerAllocator>  _tracking_status_reply_type;
  _tracking_status_reply_type tracking_status_reply;

   typedef  ::tircgo_uart::Lidar_level_reply_<ContainerAllocator>  _lidar_level_reply_type;
  _lidar_level_reply_type lidar_level_reply;





  typedef boost::shared_ptr< ::tircgo_uart::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tircgo_uart::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::tircgo_uart::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::tircgo_uart::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::tircgo_uart::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tircgo_uart::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tircgo_uart::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tircgo_uart::RobotStatus_<ContainerAllocator1> & lhs, const ::tircgo_uart::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_activated == rhs.is_activated &&
    lhs.now_mode == rhs.now_mode &&
    lhs.tracking_status_reply == rhs.tracking_status_reply &&
    lhs.lidar_level_reply == rhs.lidar_level_reply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tircgo_uart::RobotStatus_<ContainerAllocator1> & lhs, const ::tircgo_uart::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tircgo_uart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tircgo_uart::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tircgo_uart::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tircgo_uart::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "724d9103467732d3b906abe0e2db04e9";
  }

  static const char* value(const ::tircgo_uart::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x724d9103467732d3ULL;
  static const uint64_t static_value2 = 0xb906abe0e2db04e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tircgo_uart/RobotStatus";
  }

  static const char* value(const ::tircgo_uart::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool is_activated\n"
"int16 now_mode\n"
"tircgo_uart/Tracking_status_reply tracking_status_reply\n"
"tircgo_uart/Lidar_level_reply lidar_level_reply\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tircgo_uart/Tracking_status_reply\n"
"std_msgs/Header header\n"
"bool is_legal_op\n"
"bool is_activated\n"
"int16 error_code\n"
"int16 reply\n"
"\n"
"================================================================================\n"
"MSG: tircgo_uart/Lidar_level_reply\n"
"std_msgs/Header header\n"
"bool is_legal_op\n"
"bool is_activated\n"
"int16 error_code\n"
"int16[] level_reply\n"
;
  }

  static const char* value(const ::tircgo_uart::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_activated);
      stream.next(m.now_mode);
      stream.next(m.tracking_status_reply);
      stream.next(m.lidar_level_reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tircgo_uart::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tircgo_uart::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_activated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_activated);
    s << indent << "now_mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.now_mode);
    s << indent << "tracking_status_reply: ";
    s << std::endl;
    Printer< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >::stream(s, indent + "  ", v.tracking_status_reply);
    s << indent << "lidar_level_reply: ";
    s << std::endl;
    Printer< ::tircgo_uart::Lidar_level_reply_<ContainerAllocator> >::stream(s, indent + "  ", v.lidar_level_reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIRCGO_UART_MESSAGE_ROBOTSTATUS_H
