// Generated by gencpp from file tircgo_uart/Tracking_status_reply.msg
// DO NOT EDIT!


#ifndef TIRCGO_UART_MESSAGE_TRACKING_STATUS_REPLY_H
#define TIRCGO_UART_MESSAGE_TRACKING_STATUS_REPLY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tircgo_uart
{
template <class ContainerAllocator>
struct Tracking_status_reply_
{
  typedef Tracking_status_reply_<ContainerAllocator> Type;

  Tracking_status_reply_()
    : header()
    , is_legal_op(false)
    , is_activated(false)
    , error_code(0)
    , reply(0)  {
    }
  Tracking_status_reply_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_legal_op(false)
    , is_activated(false)
    , error_code(0)
    , reply(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_legal_op_type;
  _is_legal_op_type is_legal_op;

   typedef uint8_t _is_activated_type;
  _is_activated_type is_activated;

   typedef int16_t _error_code_type;
  _error_code_type error_code;

   typedef int16_t _reply_type;
  _reply_type reply;





  typedef boost::shared_ptr< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> const> ConstPtr;

}; // struct Tracking_status_reply_

typedef ::tircgo_uart::Tracking_status_reply_<std::allocator<void> > Tracking_status_reply;

typedef boost::shared_ptr< ::tircgo_uart::Tracking_status_reply > Tracking_status_replyPtr;
typedef boost::shared_ptr< ::tircgo_uart::Tracking_status_reply const> Tracking_status_replyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator1> & lhs, const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_legal_op == rhs.is_legal_op &&
    lhs.is_activated == rhs.is_activated &&
    lhs.error_code == rhs.error_code &&
    lhs.reply == rhs.reply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator1> & lhs, const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tircgo_uart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d3408e6b80e747b553974b7f98663c1";
  }

  static const char* value(const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d3408e6b80e747bULL;
  static const uint64_t static_value2 = 0x553974b7f98663c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tircgo_uart/Tracking_status_reply";
  }

  static const char* value(const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool is_legal_op\n"
"bool is_activated\n"
"int16 error_code\n"
"int16 reply\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_legal_op);
      stream.next(m.is_activated);
      stream.next(m.error_code);
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tracking_status_reply_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tircgo_uart::Tracking_status_reply_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tircgo_uart::Tracking_status_reply_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_legal_op: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_legal_op);
    s << indent << "is_activated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_activated);
    s << indent << "error_code: ";
    Printer<int16_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "reply: ";
    Printer<int16_t>::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIRCGO_UART_MESSAGE_TRACKING_STATUS_REPLY_H
