# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tircgo_uart/RobotStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import tircgo_uart.msg

class RobotStatus(genpy.Message):
  _md5sum = "724d9103467732d3b906abe0e2db04e9"
  _type = "tircgo_uart/RobotStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool is_activated
int16 now_mode
tircgo_uart/Tracking_status_reply tracking_status_reply
tircgo_uart/Lidar_level_reply lidar_level_reply


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: tircgo_uart/Tracking_status_reply
std_msgs/Header header
bool is_legal_op
bool is_activated
int16 error_code
int16 reply

================================================================================
MSG: tircgo_uart/Lidar_level_reply
std_msgs/Header header
bool is_legal_op
bool is_activated
int16 error_code
int16[] level_reply
"""
  __slots__ = ['header','is_activated','now_mode','tracking_status_reply','lidar_level_reply']
  _slot_types = ['std_msgs/Header','bool','int16','tircgo_uart/Tracking_status_reply','tircgo_uart/Lidar_level_reply']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,is_activated,now_mode,tracking_status_reply,lidar_level_reply

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.is_activated is None:
        self.is_activated = False
      if self.now_mode is None:
        self.now_mode = 0
      if self.tracking_status_reply is None:
        self.tracking_status_reply = tircgo_uart.msg.Tracking_status_reply()
      if self.lidar_level_reply is None:
        self.lidar_level_reply = tircgo_uart.msg.Lidar_level_reply()
    else:
      self.header = std_msgs.msg.Header()
      self.is_activated = False
      self.now_mode = 0
      self.tracking_status_reply = tircgo_uart.msg.Tracking_status_reply()
      self.lidar_level_reply = tircgo_uart.msg.Lidar_level_reply()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bh3I().pack(_x.is_activated, _x.now_mode, _x.tracking_status_reply.header.seq, _x.tracking_status_reply.header.stamp.secs, _x.tracking_status_reply.header.stamp.nsecs))
      _x = self.tracking_status_reply.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B2h3I().pack(_x.tracking_status_reply.is_legal_op, _x.tracking_status_reply.is_activated, _x.tracking_status_reply.error_code, _x.tracking_status_reply.reply, _x.lidar_level_reply.header.seq, _x.lidar_level_reply.header.stamp.secs, _x.lidar_level_reply.header.stamp.nsecs))
      _x = self.lidar_level_reply.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Bh().pack(_x.lidar_level_reply.is_legal_op, _x.lidar_level_reply.is_activated, _x.lidar_level_reply.error_code))
      length = len(self.lidar_level_reply.level_reply)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(struct.pack(pattern, *self.lidar_level_reply.level_reply))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.tracking_status_reply is None:
        self.tracking_status_reply = tircgo_uart.msg.Tracking_status_reply()
      if self.lidar_level_reply is None:
        self.lidar_level_reply = tircgo_uart.msg.Lidar_level_reply()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.is_activated, _x.now_mode, _x.tracking_status_reply.header.seq, _x.tracking_status_reply.header.stamp.secs, _x.tracking_status_reply.header.stamp.nsecs,) = _get_struct_Bh3I().unpack(str[start:end])
      self.is_activated = bool(self.is_activated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tracking_status_reply.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.tracking_status_reply.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.tracking_status_reply.is_legal_op, _x.tracking_status_reply.is_activated, _x.tracking_status_reply.error_code, _x.tracking_status_reply.reply, _x.lidar_level_reply.header.seq, _x.lidar_level_reply.header.stamp.secs, _x.lidar_level_reply.header.stamp.nsecs,) = _get_struct_2B2h3I().unpack(str[start:end])
      self.tracking_status_reply.is_legal_op = bool(self.tracking_status_reply.is_legal_op)
      self.tracking_status_reply.is_activated = bool(self.tracking_status_reply.is_activated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lidar_level_reply.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.lidar_level_reply.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 4
      (_x.lidar_level_reply.is_legal_op, _x.lidar_level_reply.is_activated, _x.lidar_level_reply.error_code,) = _get_struct_2Bh().unpack(str[start:end])
      self.lidar_level_reply.is_legal_op = bool(self.lidar_level_reply.is_legal_op)
      self.lidar_level_reply.is_activated = bool(self.lidar_level_reply.is_activated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      end += struct.calcsize(pattern)
      self.lidar_level_reply.level_reply = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bh3I().pack(_x.is_activated, _x.now_mode, _x.tracking_status_reply.header.seq, _x.tracking_status_reply.header.stamp.secs, _x.tracking_status_reply.header.stamp.nsecs))
      _x = self.tracking_status_reply.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B2h3I().pack(_x.tracking_status_reply.is_legal_op, _x.tracking_status_reply.is_activated, _x.tracking_status_reply.error_code, _x.tracking_status_reply.reply, _x.lidar_level_reply.header.seq, _x.lidar_level_reply.header.stamp.secs, _x.lidar_level_reply.header.stamp.nsecs))
      _x = self.lidar_level_reply.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Bh().pack(_x.lidar_level_reply.is_legal_op, _x.lidar_level_reply.is_activated, _x.lidar_level_reply.error_code))
      length = len(self.lidar_level_reply.level_reply)
      buff.write(_struct_I.pack(length))
      pattern = '<%sh'%length
      buff.write(self.lidar_level_reply.level_reply.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.tracking_status_reply is None:
        self.tracking_status_reply = tircgo_uart.msg.Tracking_status_reply()
      if self.lidar_level_reply is None:
        self.lidar_level_reply = tircgo_uart.msg.Lidar_level_reply()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.is_activated, _x.now_mode, _x.tracking_status_reply.header.seq, _x.tracking_status_reply.header.stamp.secs, _x.tracking_status_reply.header.stamp.nsecs,) = _get_struct_Bh3I().unpack(str[start:end])
      self.is_activated = bool(self.is_activated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tracking_status_reply.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.tracking_status_reply.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.tracking_status_reply.is_legal_op, _x.tracking_status_reply.is_activated, _x.tracking_status_reply.error_code, _x.tracking_status_reply.reply, _x.lidar_level_reply.header.seq, _x.lidar_level_reply.header.stamp.secs, _x.lidar_level_reply.header.stamp.nsecs,) = _get_struct_2B2h3I().unpack(str[start:end])
      self.tracking_status_reply.is_legal_op = bool(self.tracking_status_reply.is_legal_op)
      self.tracking_status_reply.is_activated = bool(self.tracking_status_reply.is_activated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lidar_level_reply.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.lidar_level_reply.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 4
      (_x.lidar_level_reply.is_legal_op, _x.lidar_level_reply.is_activated, _x.lidar_level_reply.error_code,) = _get_struct_2Bh().unpack(str[start:end])
      self.lidar_level_reply.is_legal_op = bool(self.lidar_level_reply.is_legal_op)
      self.lidar_level_reply.is_activated = bool(self.lidar_level_reply.is_activated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sh'%length
      start = end
      end += struct.calcsize(pattern)
      self.lidar_level_reply.level_reply = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2h3I = None
def _get_struct_2B2h3I():
    global _struct_2B2h3I
    if _struct_2B2h3I is None:
        _struct_2B2h3I = struct.Struct("<2B2h3I")
    return _struct_2B2h3I
_struct_2Bh = None
def _get_struct_2Bh():
    global _struct_2Bh
    if _struct_2Bh is None:
        _struct_2Bh = struct.Struct("<2Bh")
    return _struct_2Bh
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bh3I = None
def _get_struct_Bh3I():
    global _struct_Bh3I
    if _struct_Bh3I is None:
        _struct_Bh3I = struct.Struct("<Bh3I")
    return _struct_Bh3I
