(cl:defpackage tircgo_uart-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "ROBOTINVOKE"
   "<ROBOTINVOKE-REQUEST>"
   "ROBOTINVOKE-REQUEST"
   "<ROBOTINVOKE-RESPONSE>"
   "ROBOTINVOKE-RESPONSE"
  ))

